---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "ipfs-node.fullname" . }}-storage
  namespace: {{ .Release.Namespace }}
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
reclaimPolicy: {{ .Values.cluster.reclaimPolicy }}
allowVolumeExpansion: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ipfs-node.fullname" . }}-data-pvc
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName:  {{ include "ipfs-node.fullname" . }}-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volumen.resources.storage.data }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  {{ include "ipfs-node.fullname" . }}-staging-pvc 
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName:  {{ include "ipfs-node.fullname" . }}-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volumen.resources.storage.staging }}






